package cn.edu.tit.forum.model;

public class Favorite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.id
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.user_id
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.article_id
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.gmt_create
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.id
     *
     * @return the value of favorite.id
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.id
     *
     * @param id the value for favorite.id
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.user_id
     *
     * @return the value of favorite.user_id
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.user_id
     *
     * @param userId the value for favorite.user_id
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.article_id
     *
     * @return the value of favorite.article_id
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.article_id
     *
     * @param articleId the value for favorite.article_id
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.gmt_create
     *
     * @return the value of favorite.gmt_create
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.gmt_create
     *
     * @param gmtCreate the value for favorite.gmt_create
     *
     * @mbg.generated Fri May 08 22:58:41 AWST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}