package cn.edu.tit.forum.model;

public class ThumbUp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.id
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.user_id
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.target_id
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    private Long targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.type
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb_up.gmt_create
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    private Long gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.id
     *
     * @return the value of thumb_up.id
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.id
     *
     * @param id the value for thumb_up.id
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.user_id
     *
     * @return the value of thumb_up.user_id
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.user_id
     *
     * @param userId the value for thumb_up.user_id
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.target_id
     *
     * @return the value of thumb_up.target_id
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.target_id
     *
     * @param targetId the value for thumb_up.target_id
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.type
     *
     * @return the value of thumb_up.type
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.type
     *
     * @param type the value for thumb_up.type
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb_up.gmt_create
     *
     * @return the value of thumb_up.gmt_create
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb_up.gmt_create
     *
     * @param gmtCreate the value for thumb_up.gmt_create
     *
     * @mbg.generated Sat Apr 25 22:13:37 AWST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}