package cn.edu.tit.forum.model;

public class Thumb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.id
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.userid
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.typeid
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    private Long typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thumb.type
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.id
     *
     * @return the value of thumb.id
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.id
     *
     * @param id the value for thumb.id
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.userid
     *
     * @return the value of thumb.userid
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.userid
     *
     * @param userid the value for thumb.userid
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.typeid
     *
     * @return the value of thumb.typeid
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    public Long getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.typeid
     *
     * @param typeid the value for thumb.typeid
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    public void setTypeid(Long typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thumb.type
     *
     * @return the value of thumb.type
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thumb.type
     *
     * @param type the value for thumb.type
     *
     * @mbg.generated Wed Jan 01 11:09:00 AWST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }
}