package cn.edu.tit.forum.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.descript
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private String descript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.follow_count
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private Integer followCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar_url
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.identify_type
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private String identifyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.identifier
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.credential
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private String credential;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email_password
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private String emailPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_create
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gmt_modify
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    private Long gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.descript
     *
     * @return the value of user.descript
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.descript
     *
     * @param descript the value for user.descript
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setDescript(String descript) {
        this.descript = descript == null ? null : descript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.follow_count
     *
     * @return the value of user.follow_count
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public Integer getFollowCount() {
        return followCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.follow_count
     *
     * @param followCount the value for user.follow_count
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setFollowCount(Integer followCount) {
        this.followCount = followCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar_url
     *
     * @return the value of user.avatar_url
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar_url
     *
     * @param avatarUrl the value for user.avatar_url
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.identify_type
     *
     * @return the value of user.identify_type
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public String getIdentifyType() {
        return identifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.identify_type
     *
     * @param identifyType the value for user.identify_type
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setIdentifyType(String identifyType) {
        this.identifyType = identifyType == null ? null : identifyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.identifier
     *
     * @return the value of user.identifier
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.identifier
     *
     * @param identifier the value for user.identifier
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.credential
     *
     * @return the value of user.credential
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public String getCredential() {
        return credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.credential
     *
     * @param credential the value for user.credential
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setCredential(String credential) {
        this.credential = credential == null ? null : credential.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email_password
     *
     * @return the value of user.email_password
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public String getEmailPassword() {
        return emailPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email_password
     *
     * @param emailPassword the value for user.email_password
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setEmailPassword(String emailPassword) {
        this.emailPassword = emailPassword == null ? null : emailPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_create
     *
     * @return the value of user.gmt_create
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_create
     *
     * @param gmtCreate the value for user.gmt_create
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gmt_modify
     *
     * @return the value of user.gmt_modify
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gmt_modify
     *
     * @param gmtModify the value for user.gmt_modify
     *
     * @mbg.generated Tue Mar 03 22:36:24 AWST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }
}